Revert "Use abstract Connection in place of TlsConnection"
This reverts commit 92464b523ee0340dd4b321367a0cdf69a7644290.

Reason for revert: breaks the autoroller :(.

https://chromium-review.googlesource.com/c/chromium/src/+/7257264

Hate to revert but need to do that to enable the QUICHE roll.

Happy to prioritize relanding it tomorrow.

Example failures:
https://ci.chromium.org/ui/p/chromium/builders/try/android-x64-rel/726580/overview

[28250/51502] CXX obj/components/openscreen_platform/unittests/tls_client_connection_unittest.o
../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF obj/components/openscreen_platform/unittests/tls_client_connection_unittest....(too long)
../../components/openscreen_platform/tls_client_connection_unittest.cc:134:3: error: non-virtual member function marked 'override' hides virtual member function
  134 |   MOCK_METHOD(void, OnError, (TlsConnection*, const Error&), (override));
      |   ^
../../third_party/googletest/src/googlemock/include/gmock/gmock-function-mocker.h:115:3: note: expanded from macro 'MOCK_METHOD'
  115 |   GMOCK_PP_VARIADIC_CALL(GMOCK_INTERNAL_MOCK_METHOD_ARG_, __VA_ARGS__) \
      |   ^
../../third_party/googletest/src/googlemock/include/gmock/internal/gmock-pp.h:49:7: note: expanded from macro 'GMOCK_PP_VARIADIC_CALL'
   49 |       GMOCK_PP_CAT(_Macro, GMOCK_PP_NARG(__VA_ARGS__))(__VA_ARGS__))
      |       ^


Original change's description:
> Use abstract Connection in place of TlsConnection
>
> Bug: 445928621
> Change-Id: I485228f0e56ecd736f661194bb0e72d2682344db
> Reviewed-on: https://chromium-review.googlesource.com/c/openscreen/+/7247255
> Reviewed-by: Muyao Xu <muyaoxu@google.com>
> Commit-Queue: Taesun Yeoum <taesuny@google.com>
> Reviewed-by: Jordan Bayles <jophba@chromium.org>

Bug: 445928621
Change-Id: Ia3369a687a06547aea26a7f99ac48d986eddc567
Reviewed-on: https://chromium-review.googlesource.com/c/openscreen/+/7303817
Reviewed-by: Nidhi Jaju <nidhijaju@chromium.org>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>